name: Basic-CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Upgrade Stack
        run: stack upgrade --binary-only
        
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: .stack-work/
          key: stack-monolith
        
      - name: Build project
        run: stack build --test --copy-bins
        
      - uses: actions/download-artifact@v2
        with:
          name: monolith
          path: /home/runner/.local/bin
